type Country = {
  name: string;
  iso2: string | null;
  iso3: string | null;
  flag: string | null;
};

export const Countries: Array<Country> = [
  {
    name: "Afghanistan",
    iso2: "AF",
    iso3: "AFG",
    flag: "https://disease.sh/assets/img/flags/af.png",
  },
  {
    name: "Albania",
    iso2: "AL",
    iso3: "ALB",
    flag: "https://disease.sh/assets/img/flags/al.png",
  },
  {
    name: "Algeria",
    iso2: "DZ",
    iso3: "DZA",
    flag: "https://disease.sh/assets/img/flags/dz.png",
  },
  {
    name: "Andorra",
    iso2: "AD",
    iso3: "AND",
    flag: "https://disease.sh/assets/img/flags/ad.png",
  },
  {
    name: "Angola",
    iso2: "AO",
    iso3: "AGO",
    flag: "https://disease.sh/assets/img/flags/ao.png",
  },
  {
    name: "Anguilla",
    iso2: "AI",
    iso3: "AIA",
    flag: "https://disease.sh/assets/img/flags/ai.png",
  },
  {
    name: "Antigua and Barbuda",
    iso2: "AG",
    iso3: "ATG",
    flag: "https://disease.sh/assets/img/flags/ag.png",
  },
  {
    name: "Argentina",
    iso2: "AR",
    iso3: "ARG",
    flag: "https://disease.sh/assets/img/flags/ar.png",
  },
  {
    name: "Armenia",
    iso2: "AM",
    iso3: "ARM",
    flag: "https://disease.sh/assets/img/flags/am.png",
  },
  {
    name: "Aruba",
    iso2: "AW",
    iso3: "ABW",
    flag: "https://disease.sh/assets/img/flags/aw.png",
  },
  {
    name: "Australia",
    iso2: "AU",
    iso3: "AUS",
    flag: "https://disease.sh/assets/img/flags/au.png",
  },
  {
    name: "Austria",
    iso2: "AT",
    iso3: "AUT",
    flag: "https://disease.sh/assets/img/flags/at.png",
  },
  {
    name: "Azerbaijan",
    iso2: "AZ",
    iso3: "AZE",
    flag: "https://disease.sh/assets/img/flags/az.png",
  },
  {
    name: "Bahamas",
    iso2: "BS",
    iso3: "BHS",
    flag: "https://disease.sh/assets/img/flags/bs.png",
  },
  {
    name: "Bahrain",
    iso2: "BH",
    iso3: "BHR",
    flag: "https://disease.sh/assets/img/flags/bh.png",
  },
  {
    name: "Bangladesh",
    iso2: "BD",
    iso3: "BGD",
    flag: "https://disease.sh/assets/img/flags/bd.png",
  },
  {
    name: "Barbados",
    iso2: "BB",
    iso3: "BRB",
    flag: "https://disease.sh/assets/img/flags/bb.png",
  },
  {
    name: "Belarus",
    iso2: "BY",
    iso3: "BLR",
    flag: "https://disease.sh/assets/img/flags/by.png",
  },
  {
    name: "Belgium",
    iso2: "BE",
    iso3: "BEL",
    flag: "https://disease.sh/assets/img/flags/be.png",
  },
  {
    name: "Belize",
    iso2: "BZ",
    iso3: "BLZ",
    flag: "https://disease.sh/assets/img/flags/bz.png",
  },
  {
    name: "Benin",
    iso2: "BJ",
    iso3: "BEN",
    flag: "https://disease.sh/assets/img/flags/bj.png",
  },
  {
    name: "Bermuda",
    iso2: "BM",
    iso3: "BMU",
    flag: "https://disease.sh/assets/img/flags/bm.png",
  },
  {
    name: "Bhutan",
    iso2: "BT",
    iso3: "BTN",
    flag: "https://disease.sh/assets/img/flags/bt.png",
  },
  {
    name: "Bolivia",
    iso2: "BO",
    iso3: "BOL",
    flag: "https://disease.sh/assets/img/flags/bo.png",
  },
  {
    name: "Bosnia",
    iso2: "BA",
    iso3: "BIH",
    flag: "https://disease.sh/assets/img/flags/ba.png",
  },
  {
    name: "Botswana",
    iso2: "BW",
    iso3: "BWA",
    flag: "https://disease.sh/assets/img/flags/bw.png",
  },
  {
    name: "Brazil",
    iso2: "BR",
    iso3: "BRA",
    flag: "https://disease.sh/assets/img/flags/br.png",
  },
  {
    name: "British Virgin Islands",
    iso2: "VG",
    iso3: "VGB",
    flag: "https://disease.sh/assets/img/flags/vg.png",
  },
  {
    name: "Brunei",
    iso2: "BN",
    iso3: "BRN",
    flag: "https://disease.sh/assets/img/flags/bn.png",
  },
  {
    name: "Bulgaria",
    iso2: "BG",
    iso3: "BGR",
    flag: "https://disease.sh/assets/img/flags/bg.png",
  },
  {
    name: "Burkina Faso",
    iso2: "BF",
    iso3: "BFA",
    flag: "https://disease.sh/assets/img/flags/bf.png",
  },
  {
    name: "Burundi",
    iso2: "BI",
    iso3: "BDI",
    flag: "https://disease.sh/assets/img/flags/bi.png",
  },
  {
    name: "Cabo Verde",
    iso2: "CV",
    iso3: "CPV",
    flag: "https://disease.sh/assets/img/flags/cv.png",
  },
  {
    name: "Cambodia",
    iso2: "KH",
    iso3: "KHM",
    flag: "https://disease.sh/assets/img/flags/kh.png",
  },
  {
    name: "Cameroon",
    iso2: "CM",
    iso3: "CMR",
    flag: "https://disease.sh/assets/img/flags/cm.png",
  },
  {
    name: "Canada",
    iso2: "CA",
    iso3: "CAN",
    flag: "https://disease.sh/assets/img/flags/ca.png",
  },
  {
    name: "Caribbean Netherlands",
    iso2: "BQ",
    iso3: "BES",
    flag: "https://disease.sh/assets/img/flags/bq.png",
  },
  {
    name: "Cayman Islands",
    iso2: "KY",
    iso3: "CYM",
    flag: "https://disease.sh/assets/img/flags/ky.png",
  },
  {
    name: "Central African Republic",
    iso2: "CF",
    iso3: "CAF",
    flag: "https://disease.sh/assets/img/flags/cf.png",
  },
  {
    name: "Chad",
    iso2: "TD",
    iso3: "TCD",
    flag: "https://disease.sh/assets/img/flags/td.png",
  },
  {
    name: "Channel Islands",
    iso2: "JE",
    iso3: "JEY",
    flag: "https://disease.sh/assets/img/flags/je.png",
  },
  {
    name: "Chile",
    iso2: "CL",
    iso3: "CHL",
    flag: "https://disease.sh/assets/img/flags/cl.png",
  },
  {
    name: "China",
    iso2: "CN",
    iso3: "CHN",
    flag: "https://disease.sh/assets/img/flags/cn.png",
  },
  {
    name: "Colombia",
    iso2: "CO",
    iso3: "COL",
    flag: "https://disease.sh/assets/img/flags/co.png",
  },
  {
    name: "Comoros",
    iso2: "KM",
    iso3: "COM",
    flag: "https://disease.sh/assets/img/flags/km.png",
  },
  {
    name: "Congo",
    iso2: "CG",
    iso3: "COG",
    flag: "https://disease.sh/assets/img/flags/cg.png",
  },
  {
    name: "Costa Rica",
    iso2: "CR",
    iso3: "CRI",
    flag: "https://disease.sh/assets/img/flags/cr.png",
  },
  {
    name: "Croatia",
    iso2: "HR",
    iso3: "HRV",
    flag: "https://disease.sh/assets/img/flags/hr.png",
  },
  {
    name: "Cuba",
    iso2: "CU",
    iso3: "CUB",
    flag: "https://disease.sh/assets/img/flags/cu.png",
  },
  {
    name: "Curaçao",
    iso2: "CW",
    iso3: "CUW",
    flag: "https://disease.sh/assets/img/flags/cw.png",
  },
  {
    name: "Cyprus",
    iso2: "CY",
    iso3: "CYP",
    flag: "https://disease.sh/assets/img/flags/cy.png",
  },
  {
    name: "Czechia",
    iso2: "CZ",
    iso3: "CZE",
    flag: "https://disease.sh/assets/img/flags/cz.png",
  },
  {
    name: "Côte d'Ivoire",
    iso2: "CI",
    iso3: "CIV",
    flag: "https://disease.sh/assets/img/flags/ci.png",
  },
  {
    name: "DRC",
    iso2: "CD",
    iso3: "COD",
    flag: "https://disease.sh/assets/img/flags/cd.png",
  },
  {
    name: "Denmark",
    iso2: "DK",
    iso3: "DNK",
    flag: "https://disease.sh/assets/img/flags/dk.png",
  },
  {
    name: "Diamond Princess",
    iso2: null,
    iso3: null,
    flag: "https://disease.sh/assets/img/flags/unknown.png",
  },
  {
    name: "Djibouti",
    iso2: "DJ",
    iso3: "DJI",
    flag: "https://disease.sh/assets/img/flags/dj.png",
  },
  {
    name: "Dominica",
    iso2: "DM",
    iso3: "DMA",
    flag: "https://disease.sh/assets/img/flags/dm.png",
  },
  {
    name: "Dominican Republic",
    iso2: "DO",
    iso3: "DOM",
    flag: "https://disease.sh/assets/img/flags/do.png",
  },
  {
    name: "Ecuador",
    iso2: "EC",
    iso3: "ECU",
    flag: "https://disease.sh/assets/img/flags/ec.png",
  },
  {
    name: "Egypt",
    iso2: "EG",
    iso3: "EGY",
    flag: "https://disease.sh/assets/img/flags/eg.png",
  },
  {
    name: "El Salvador",
    iso2: "SV",
    iso3: "SLV",
    flag: "https://disease.sh/assets/img/flags/sv.png",
  },
  {
    name: "Equatorial Guinea",
    iso2: "GQ",
    iso3: "GNQ",
    flag: "https://disease.sh/assets/img/flags/gq.png",
  },
  {
    name: "Eritrea",
    iso2: "ER",
    iso3: "ERI",
    flag: "https://disease.sh/assets/img/flags/er.png",
  },
  {
    name: "Estonia",
    iso2: "EE",
    iso3: "EST",
    flag: "https://disease.sh/assets/img/flags/ee.png",
  },
  {
    name: "Ethiopia",
    iso2: "ET",
    iso3: "ETH",
    flag: "https://disease.sh/assets/img/flags/et.png",
  },
  {
    name: "Falkland Islands (Malvinas)",
    iso2: "FK",
    iso3: "FLK",
    flag: "https://disease.sh/assets/img/flags/fk.png",
  },
  {
    name: "Faroe Islands",
    iso2: "FO",
    iso3: "FRO",
    flag: "https://disease.sh/assets/img/flags/fo.png",
  },
  {
    name: "Fiji",
    iso2: "FJ",
    iso3: "FJI",
    flag: "https://disease.sh/assets/img/flags/fj.png",
  },
  {
    name: "Finland",
    iso2: "FI",
    iso3: "FIN",
    flag: "https://disease.sh/assets/img/flags/fi.png",
  },
  {
    name: "France",
    iso2: "FR",
    iso3: "FRA",
    flag: "https://disease.sh/assets/img/flags/fr.png",
  },
  {
    name: "French Guiana",
    iso2: "GF",
    iso3: "GUF",
    flag: "https://disease.sh/assets/img/flags/gf.png",
  },
  {
    name: "French Polynesia",
    iso2: "PF",
    iso3: "PYF",
    flag: "https://disease.sh/assets/img/flags/pf.png",
  },
  {
    name: "Gabon",
    iso2: "GA",
    iso3: "GAB",
    flag: "https://disease.sh/assets/img/flags/ga.png",
  },
  {
    name: "Gambia",
    iso2: "GM",
    iso3: "GMB",
    flag: "https://disease.sh/assets/img/flags/gm.png",
  },
  {
    name: "Georgia",
    iso2: "GE",
    iso3: "GEO",
    flag: "https://disease.sh/assets/img/flags/ge.png",
  },
  {
    name: "Germany",
    iso2: "DE",
    iso3: "DEU",
    flag: "https://disease.sh/assets/img/flags/de.png",
  },
  {
    name: "Ghana",
    iso2: "GH",
    iso3: "GHA",
    flag: "https://disease.sh/assets/img/flags/gh.png",
  },
  {
    name: "Gibraltar",
    iso2: "GI",
    iso3: "GIB",
    flag: "https://disease.sh/assets/img/flags/gi.png",
  },
  {
    name: "Greece",
    iso2: "GR",
    iso3: "GRC",
    flag: "https://disease.sh/assets/img/flags/gr.png",
  },
  {
    name: "Greenland",
    iso2: "GL",
    iso3: "GRL",
    flag: "https://disease.sh/assets/img/flags/gl.png",
  },
  {
    name: "Grenada",
    iso2: "GD",
    iso3: "GRD",
    flag: "https://disease.sh/assets/img/flags/gd.png",
  },
  {
    name: "Guadeloupe",
    iso2: "GP",
    iso3: "GLP",
    flag: "https://disease.sh/assets/img/flags/gp.png",
  },
  {
    name: "Guatemala",
    iso2: "GT",
    iso3: "GTM",
    flag: "https://disease.sh/assets/img/flags/gt.png",
  },
  {
    name: "Guinea",
    iso2: "GN",
    iso3: "GIN",
    flag: "https://disease.sh/assets/img/flags/gn.png",
  },
  {
    name: "Guinea-Bissau",
    iso2: "GW",
    iso3: "GNB",
    flag: "https://disease.sh/assets/img/flags/gw.png",
  },
  {
    name: "Guyana",
    iso2: "GY",
    iso3: "GUY",
    flag: "https://disease.sh/assets/img/flags/gy.png",
  },
  {
    name: "Haiti",
    iso2: "HT",
    iso3: "HTI",
    flag: "https://disease.sh/assets/img/flags/ht.png",
  },
  {
    name: "Holy See (Vatican City State)",
    iso2: "VA",
    iso3: "VAT",
    flag: "https://disease.sh/assets/img/flags/va.png",
  },
  {
    name: "Honduras",
    iso2: "HN",
    iso3: "HND",
    flag: "https://disease.sh/assets/img/flags/hn.png",
  },
  {
    name: "Hong Kong",
    iso2: "HK",
    iso3: "HKG",
    flag: "https://disease.sh/assets/img/flags/hk.png",
  },
  {
    name: "Hungary",
    iso2: "HU",
    iso3: "HUN",
    flag: "https://disease.sh/assets/img/flags/hu.png",
  },
  {
    name: "Iceland",
    iso2: "IS",
    iso3: "ISL",
    flag: "https://disease.sh/assets/img/flags/is.png",
  },
  {
    name: "India",
    iso2: "IN",
    iso3: "IND",
    flag: "https://disease.sh/assets/img/flags/in.png",
  },
  {
    name: "Indonesia",
    iso2: "ID",
    iso3: "IDN",
    flag: "https://disease.sh/assets/img/flags/id.png",
  },
  {
    name: "Iran",
    iso2: "IR",
    iso3: "IRN",
    flag: "https://disease.sh/assets/img/flags/ir.png",
  },
  {
    name: "Iraq",
    iso2: "IQ",
    iso3: "IRQ",
    flag: "https://disease.sh/assets/img/flags/iq.png",
  },
  {
    name: "Ireland",
    iso2: "IE",
    iso3: "IRL",
    flag: "https://disease.sh/assets/img/flags/ie.png",
  },
  {
    name: "Isle of Man",
    iso2: "IM",
    iso3: "IMN",
    flag: "https://disease.sh/assets/img/flags/im.png",
  },
  {
    name: "Israel",
    iso2: "IL",
    iso3: "ISR",
    flag: "https://disease.sh/assets/img/flags/il.png",
  },
  {
    name: "Italy",
    iso2: "IT",
    iso3: "ITA",
    flag: "https://disease.sh/assets/img/flags/it.png",
  },
  {
    name: "Jamaica",
    iso2: "JM",
    iso3: "JAM",
    flag: "https://disease.sh/assets/img/flags/jm.png",
  },
  {
    name: "Japan",
    iso2: "JP",
    iso3: "JPN",
    flag: "https://disease.sh/assets/img/flags/jp.png",
  },
  {
    name: "Jordan",
    iso2: "JO",
    iso3: "JOR",
    flag: "https://disease.sh/assets/img/flags/jo.png",
  },
  {
    name: "Kazakhstan",
    iso2: "KZ",
    iso3: "KAZ",
    flag: "https://disease.sh/assets/img/flags/kz.png",
  },
  {
    name: "Kenya",
    iso2: "KE",
    iso3: "KEN",
    flag: "https://disease.sh/assets/img/flags/ke.png",
  },
  {
    name: "Kuwait",
    iso2: "KW",
    iso3: "KWT",
    flag: "https://disease.sh/assets/img/flags/kw.png",
  },
  {
    name: "Kyrgyzstan",
    iso2: "KG",
    iso3: "KGZ",
    flag: "https://disease.sh/assets/img/flags/kg.png",
  },
  {
    name: "Lao People's Democratic Republic",
    iso2: "LA",
    iso3: "LAO",
    flag: "https://disease.sh/assets/img/flags/la.png",
  },
  {
    name: "Latvia",
    iso2: "LV",
    iso3: "LVA",
    flag: "https://disease.sh/assets/img/flags/lv.png",
  },
  {
    name: "Lebanon",
    iso2: "LB",
    iso3: "LBN",
    flag: "https://disease.sh/assets/img/flags/lb.png",
  },
  {
    name: "Liberia",
    iso2: "LR",
    iso3: "LBR",
    flag: "https://disease.sh/assets/img/flags/lr.png",
  },
  {
    name: "Libyan Arab Jamahiriya",
    iso2: "LY",
    iso3: "LBY",
    flag: "https://disease.sh/assets/img/flags/ly.png",
  },
  {
    name: "Liechtenstein",
    iso2: "LI",
    iso3: "LIE",
    flag: "https://disease.sh/assets/img/flags/li.png",
  },
  {
    name: "Lithuania",
    iso2: "LT",
    iso3: "LTU",
    flag: "https://disease.sh/assets/img/flags/lt.png",
  },
  {
    name: "Luxembourg",
    iso2: "LU",
    iso3: "LUX",
    flag: "https://disease.sh/assets/img/flags/lu.png",
  },
  {
    name: "MS Zaandam",
    iso2: null,
    iso3: null,
    flag: "https://disease.sh/assets/img/flags/unknown.png",
  },
  {
    name: "Macao",
    iso2: "MO",
    iso3: "MAC",
    flag: "https://disease.sh/assets/img/flags/mo.png",
  },
  {
    name: "Macedonia",
    iso2: "MK",
    iso3: "MKD",
    flag: "https://disease.sh/assets/img/flags/mk.png",
  },
  {
    name: "Madagascar",
    iso2: "MG",
    iso3: "MDG",
    flag: "https://disease.sh/assets/img/flags/mg.png",
  },
  {
    name: "Malawi",
    iso2: "MW",
    iso3: "MWI",
    flag: "https://disease.sh/assets/img/flags/mw.png",
  },
  {
    name: "Malaysia",
    iso2: "MY",
    iso3: "MYS",
    flag: "https://disease.sh/assets/img/flags/my.png",
  },
  {
    name: "Maldives",
    iso2: "MV",
    iso3: "MDV",
    flag: "https://disease.sh/assets/img/flags/mv.png",
  },
  {
    name: "Mali",
    iso2: "ML",
    iso3: "MLI",
    flag: "https://disease.sh/assets/img/flags/ml.png",
  },
  {
    name: "Malta",
    iso2: "MT",
    iso3: "MLT",
    flag: "https://disease.sh/assets/img/flags/mt.png",
  },
  {
    name: "Martinique",
    iso2: "MQ",
    iso3: "MTQ",
    flag: "https://disease.sh/assets/img/flags/mq.png",
  },
  {
    name: "Mauritania",
    iso2: "MR",
    iso3: "MRT",
    flag: "https://disease.sh/assets/img/flags/mr.png",
  },
  {
    name: "Mauritius",
    iso2: "MU",
    iso3: "MUS",
    flag: "https://disease.sh/assets/img/flags/mu.png",
  },
  {
    name: "Mayotte",
    iso2: "YT",
    iso3: "MYT",
    flag: "https://disease.sh/assets/img/flags/yt.png",
  },
  {
    name: "Mexico",
    iso2: "MX",
    iso3: "MEX",
    flag: "https://disease.sh/assets/img/flags/mx.png",
  },
  {
    name: "Moldova",
    iso2: "MD",
    iso3: "MDA",
    flag: "https://disease.sh/assets/img/flags/md.png",
  },
  {
    name: "Monaco",
    iso2: "MC",
    iso3: "MCO",
    flag: "https://disease.sh/assets/img/flags/mc.png",
  },
  {
    name: "Mongolia",
    iso2: "MN",
    iso3: "MNG",
    flag: "https://disease.sh/assets/img/flags/mn.png",
  },
  {
    name: "Montenegro",
    iso2: "ME",
    iso3: "MNE",
    flag: "https://disease.sh/assets/img/flags/me.png",
  },
  {
    name: "Montserrat",
    iso2: "MS",
    iso3: "MSR",
    flag: "https://disease.sh/assets/img/flags/ms.png",
  },
  {
    name: "Morocco",
    iso2: "MA",
    iso3: "MAR",
    flag: "https://disease.sh/assets/img/flags/ma.png",
  },
  {
    name: "Mozambique",
    iso2: "MZ",
    iso3: "MOZ",
    flag: "https://disease.sh/assets/img/flags/mz.png",
  },
  {
    name: "Myanmar",
    iso2: "MM",
    iso3: "MMR",
    flag: "https://disease.sh/assets/img/flags/mm.png",
  },
  {
    name: "Namibia",
    iso2: "NA",
    iso3: "NAM",
    flag: "https://disease.sh/assets/img/flags/na.png",
  },
  {
    name: "Nepal",
    iso2: "NP",
    iso3: "NPL",
    flag: "https://disease.sh/assets/img/flags/np.png",
  },
  {
    name: "Netherlands",
    iso2: "NL",
    iso3: "NLD",
    flag: "https://disease.sh/assets/img/flags/nl.png",
  },
  {
    name: "New Caledonia",
    iso2: "NC",
    iso3: "NCL",
    flag: "https://disease.sh/assets/img/flags/nc.png",
  },
  {
    name: "New Zealand",
    iso2: "NZ",
    iso3: "NZL",
    flag: "https://disease.sh/assets/img/flags/nz.png",
  },
  {
    name: "Nicaragua",
    iso2: "NI",
    iso3: "NIC",
    flag: "https://disease.sh/assets/img/flags/ni.png",
  },
  {
    name: "Niger",
    iso2: "NE",
    iso3: "NER",
    flag: "https://disease.sh/assets/img/flags/ne.png",
  },
  {
    name: "Nigeria",
    iso2: "NG",
    iso3: "NGA",
    flag: "https://disease.sh/assets/img/flags/ng.png",
  },
  {
    name: "Norway",
    iso2: "NO",
    iso3: "NOR",
    flag: "https://disease.sh/assets/img/flags/no.png",
  },
  {
    name: "Oman",
    iso2: "OM",
    iso3: "OMN",
    flag: "https://disease.sh/assets/img/flags/om.png",
  },
  {
    name: "Pakistan",
    iso2: "PK",
    iso3: "PAK",
    flag: "https://disease.sh/assets/img/flags/pk.png",
  },
  {
    name: "Palestine",
    iso2: "PS",
    iso3: "PSE",
    flag: "https://disease.sh/assets/img/flags/ps.png",
  },
  {
    name: "Panama",
    iso2: "PA",
    iso3: "PAN",
    flag: "https://disease.sh/assets/img/flags/pa.png",
  },
  {
    name: "Papua New Guinea",
    iso2: "PG",
    iso3: "PNG",
    flag: "https://disease.sh/assets/img/flags/pg.png",
  },
  {
    name: "Paraguay",
    iso2: "PY",
    iso3: "PRY",
    flag: "https://disease.sh/assets/img/flags/py.png",
  },
  {
    name: "Peru",
    iso2: "PE",
    iso3: "PER",
    flag: "https://disease.sh/assets/img/flags/pe.png",
  },
  {
    name: "Philippines",
    iso2: "PH",
    iso3: "PHL",
    flag: "https://disease.sh/assets/img/flags/ph.png",
  },
  {
    name: "Poland",
    iso2: "PL",
    iso3: "POL",
    flag: "https://disease.sh/assets/img/flags/pl.png",
  },
  {
    name: "Portugal",
    iso2: "PT",
    iso3: "PRT",
    flag: "https://disease.sh/assets/img/flags/pt.png",
  },
  {
    name: "Qatar",
    iso2: "QA",
    iso3: "QAT",
    flag: "https://disease.sh/assets/img/flags/qa.png",
  },
  {
    name: "Romania",
    iso2: "RO",
    iso3: "ROU",
    flag: "https://disease.sh/assets/img/flags/ro.png",
  },
  {
    name: "Russia",
    iso2: "RU",
    iso3: "RUS",
    flag: "https://disease.sh/assets/img/flags/ru.png",
  },
  {
    name: "Rwanda",
    iso2: "RW",
    iso3: "RWA",
    flag: "https://disease.sh/assets/img/flags/rw.png",
  },
  {
    name: "Réunion",
    iso2: "RE",
    iso3: "REU",
    flag: "https://disease.sh/assets/img/flags/re.png",
  },
  {
    name: "S. Korea",
    iso2: "KR",
    iso3: "KOR",
    flag: "https://disease.sh/assets/img/flags/kr.png",
  },
  {
    name: "Saint Kitts and Nevis",
    iso2: "KN",
    iso3: "KNA",
    flag: "https://disease.sh/assets/img/flags/kn.png",
  },
  {
    name: "Saint Lucia",
    iso2: "LC",
    iso3: "LCA",
    flag: "https://disease.sh/assets/img/flags/lc.png",
  },
  {
    name: "Saint Martin",
    iso2: "MF",
    iso3: "MAF",
    flag: "https://disease.sh/assets/img/flags/mf.png",
  },
  {
    name: "Saint Pierre Miquelon",
    iso2: "PM",
    iso3: "SPM",
    flag: "https://disease.sh/assets/img/flags/pm.png",
  },
  {
    name: "Saint Vincent and the Grenadines",
    iso2: "VC",
    iso3: "VCT",
    flag: "https://disease.sh/assets/img/flags/vc.png",
  },
  {
    name: "San Marino",
    iso2: "SM",
    iso3: "SMR",
    flag: "https://disease.sh/assets/img/flags/sm.png",
  },
  {
    name: "Sao Tome and Principe",
    iso2: "ST",
    iso3: "STP",
    flag: "https://disease.sh/assets/img/flags/st.png",
  },
  {
    name: "Saudi Arabia",
    iso2: "SA",
    iso3: "SAU",
    flag: "https://disease.sh/assets/img/flags/sa.png",
  },
  {
    name: "Senegal",
    iso2: "SN",
    iso3: "SEN",
    flag: "https://disease.sh/assets/img/flags/sn.png",
  },
  {
    name: "Serbia",
    iso2: "RS",
    iso3: "SRB",
    flag: "https://disease.sh/assets/img/flags/rs.png",
  },
  {
    name: "Seychelles",
    iso2: "SC",
    iso3: "SYC",
    flag: "https://disease.sh/assets/img/flags/sc.png",
  },
  {
    name: "Sierra Leone",
    iso2: "SL",
    iso3: "SLE",
    flag: "https://disease.sh/assets/img/flags/sl.png",
  },
  {
    name: "Singapore",
    iso2: "SG",
    iso3: "SGP",
    flag: "https://disease.sh/assets/img/flags/sg.png",
  },
  {
    name: "Sint Maarten",
    iso2: "SX",
    iso3: "SXM",
    flag: "https://disease.sh/assets/img/flags/sx.png",
  },
  {
    name: "Slovakia",
    iso2: "SK",
    iso3: "SVK",
    flag: "https://disease.sh/assets/img/flags/sk.png",
  },
  {
    name: "Slovenia",
    iso2: "SI",
    iso3: "SVN",
    flag: "https://disease.sh/assets/img/flags/si.png",
  },
  {
    name: "Somalia",
    iso2: "SO",
    iso3: "SOM",
    flag: "https://disease.sh/assets/img/flags/so.png",
  },
  {
    name: "South Africa",
    iso2: "ZA",
    iso3: "ZAF",
    flag: "https://disease.sh/assets/img/flags/za.png",
  },
  {
    name: "South Sudan",
    iso2: "SS",
    iso3: "SSD",
    flag: "https://disease.sh/assets/img/flags/ss.png",
  },
  {
    name: "Spain",
    iso2: "ES",
    iso3: "ESP",
    flag: "https://disease.sh/assets/img/flags/es.png",
  },
  {
    name: "Sri Lanka",
    iso2: "LK",
    iso3: "LKA",
    flag: "https://disease.sh/assets/img/flags/lk.png",
  },
  {
    name: "St. Barth",
    iso2: "BL",
    iso3: "BLM",
    flag: "https://disease.sh/assets/img/flags/bl.png",
  },
  {
    name: "Sudan",
    iso2: "SD",
    iso3: "SDN",
    flag: "https://disease.sh/assets/img/flags/sd.png",
  },
  {
    name: "Suriname",
    iso2: "SR",
    iso3: "SUR",
    flag: "https://disease.sh/assets/img/flags/sr.png",
  },
  {
    name: "Swaziland",
    iso2: "SZ",
    iso3: "SWZ",
    flag: "https://disease.sh/assets/img/flags/sz.png",
  },
  {
    name: "Sweden",
    iso2: "SE",
    iso3: "SWE",
    flag: "https://disease.sh/assets/img/flags/se.png",
  },
  {
    name: "Switzerland",
    iso2: "CH",
    iso3: "CHE",
    flag: "https://disease.sh/assets/img/flags/ch.png",
  },
  {
    name: "Syrian Arab Republic",
    iso2: "SY",
    iso3: "SYR",
    flag: "https://disease.sh/assets/img/flags/sy.png",
  },
  {
    name: "Taiwan",
    iso2: "TW",
    iso3: "TWN",
    flag: "https://disease.sh/assets/img/flags/tw.png",
  },
  {
    name: "Tajikistan",
    iso2: "TJ",
    iso3: "TJK",
    flag: "https://disease.sh/assets/img/flags/tj.png",
  },
  {
    name: "Tanzania",
    iso2: "TZ",
    iso3: "TZA",
    flag: "https://disease.sh/assets/img/flags/tz.png",
  },
  {
    name: "Thailand",
    iso2: "TH",
    iso3: "THA",
    flag: "https://disease.sh/assets/img/flags/th.png",
  },
  {
    name: "Timor-Leste",
    iso2: "TL",
    iso3: "TLS",
    flag: "https://disease.sh/assets/img/flags/tl.png",
  },
  {
    name: "Togo",
    iso2: "TG",
    iso3: "TGO",
    flag: "https://disease.sh/assets/img/flags/tg.png",
  },
  {
    name: "Trinidad and Tobago",
    iso2: "TT",
    iso3: "TTO",
    flag: "https://disease.sh/assets/img/flags/tt.png",
  },
  {
    name: "Tunisia",
    iso2: "TN",
    iso3: "TUN",
    flag: "https://disease.sh/assets/img/flags/tn.png",
  },
  {
    name: "Turkey",
    iso2: "TR",
    iso3: "TUR",
    flag: "https://disease.sh/assets/img/flags/tr.png",
  },
  {
    name: "Turks and Caicos Islands",
    iso2: "TC",
    iso3: "TCA",
    flag: "https://disease.sh/assets/img/flags/tc.png",
  },
  {
    name: "United Arab Emirates",
    iso2: "AE",
    iso3: "UAE",
    flag: "https://disease.sh/assets/img/flags/ae.png",
  },
  {
    name: "United Kingdom",
    iso2: "GB",
    iso3: "GBR",
    flag: "https://disease.sh/assets/img/flags/gb.png",
  },
  {
    name: "United States of America",
    iso2: "US",
    iso3: "USA",
    flag: "https://disease.sh/assets/img/flags/us.png",
  },
  {
    name: "Uganda",
    iso2: "UG",
    iso3: "UGA",
    flag: "https://disease.sh/assets/img/flags/ug.png",
  },
  {
    name: "Ukraine",
    iso2: "UA",
    iso3: "UKR",
    flag: "https://disease.sh/assets/img/flags/ua.png",
  },
  {
    name: "Uruguay",
    iso2: "UY",
    iso3: "URY",
    flag: "https://disease.sh/assets/img/flags/uy.png",
  },
  {
    name: "Uzbekistan",
    iso2: "UZ",
    iso3: "UZB",
    flag: "https://disease.sh/assets/img/flags/uz.png",
  },
  {
    name: "Venezuela",
    iso2: "VE",
    iso3: "VEN",
    flag: "https://disease.sh/assets/img/flags/ve.png",
  },
  {
    name: "Vietnam",
    iso2: "VN",
    iso3: "VNM",
    flag: "https://disease.sh/assets/img/flags/vn.png",
  },
  {
    name: "Western Sahara",
    iso2: "EH",
    iso3: "ESH",
    flag: "https://disease.sh/assets/img/flags/eh.png",
  },
  {
    name: "Yemen",
    iso2: "YE",
    iso3: "YEM",
    flag: "https://disease.sh/assets/img/flags/ye.png",
  },
  {
    name: "Zambia",
    iso2: "ZM",
    iso3: "ZMB",
    flag: "https://disease.sh/assets/img/flags/zm.png",
  },
  {
    name: "Zimbabwe",
    iso2: "ZW",
    iso3: "ZWE",
    flag: "https://disease.sh/assets/img/flags/zw.png",
  },
];
